kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codegen-rhdh-test-app-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: codegen-rhdh-test-app-dsp-job
    namespace: rhdh-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codegen-rhdh-test-app-dsp-job-role